# Generated by Django 5.1.15 on 2026-10-02 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_is_premium_postimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Réponse')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='blog.post')),
            ],
            options={
                'verbose_name': 'Question / Réponse (FAQ)',
                'verbose_name_plural': 'Foire Aux Questions (FAQ)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
