# Generated by Django 5.1.15 on 2026-10-03 19:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postfaq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'Article de blog', 'verbose_name_plural': 'Articles de blog'},
        ),
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text="Date et heure de publication. Si fixée dans le futur, l'article sera automatiquement planifié et restera invisible au public jusqu'à cette échéance.", verbose_name='Date et heure de publication'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text="Contenu de l'article (supporte simultanément Markdown, HTML riche et Texte brut)"),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Décocher pour conserver sous forme de brouillon.', verbose_name="Publier l'article"),
        ),
    ]
