# Generated by Django 5.2.17 on 2026-09-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Guide du Potager Tropical', max_length=200, verbose_name="Titre de l'application")),
                ('subtitle', models.CharField(default='Manuel de Maraîchage Agro-écologique & Sahélien', max_length=300, verbose_name='Sous-titre / Slogan')),
                ('mission_title', models.CharField(default='Notre Mission', max_length=200, verbose_name='Titre de la mission')),
                ('mission_text', models.TextField(default="Le Guide du Potager Tropical a été conçu pour accompagner les maraîchers urbains, périurbains et ruraux dans la transition vers une agriculture durable, rentable et résiliente face aux défis climatiques tropicaux.\n\nFace à la chaleur extrême, aux périodes d'harmattan et aux pressions parasitaires élevées en zone intertropicale, notre méthode privilégie la santé des sols, les semences adaptées et les biopesticides locaux 100% naturels (macérations de neem, purins végétaux, cendre de bois tamisée, savon noir).", help_text='Prend en charge le formatage texte ou HTML riche (<p>, <strong>, etc.)', verbose_name='Texte de présentation & Mission')),
                ('pillar_1_title', models.CharField(default="Gestion de l'Eau", max_length=150, verbose_name='Pilier 1 - Titre')),
                ('pillar_1_desc', models.TextField(default='Paillage épais obligatoire, irrigation goutte-à-goutte et économie hydrique sous forte évapotranspiration.', verbose_name='Pilier 1 - Description')),
                ('pillar_2_title', models.CharField(default='Sols Vivants', max_length=150, verbose_name='Pilier 2 - Titre')),
                ('pillar_2_desc', models.TextField(default='Compostage local, fumure organique mûre et travail superficiel sans retournement pour protéger la microfaune.', verbose_name='Pilier 2 - Description')),
                ('pillar_3_title', models.CharField(default='Zéro Chimique', max_length=150, verbose_name='Pilier 3 - Titre')),
                ('pillar_3_desc', models.TextField(default='Protection intégrée des cultures, toiles anti-insectes 50 mesh et biocontrôle à base de plantes locales.', verbose_name='Pilier 3 - Description')),
                ('contact_title', models.CharField(default='Assistance & Communauté', max_length=200, verbose_name='Titre section contact')),
                ('contact_text', models.TextField(default="Pour toute question agronomique, assistance technique sur vos abonnements ou partenariat d'exploitation, notre équipe est à votre écoute :", verbose_name='Texte section contact')),
                ('contact_email', models.EmailField(default='contact@guidedupotager.com', max_length=254, verbose_name='Email support')),
                ('contact_phone', models.CharField(default='+221 77 000 00 00', max_length=50, verbose_name='Téléphone / WhatsApp')),
                ('app_version', models.CharField(default='1.0.0', max_length=50, verbose_name="Version de l'application")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page À Propos & Mission',
                'verbose_name_plural': 'Page À Propos & Mission',
            },
        ),
    ]
