# Generated by Django 5.2.17 on 2026-09-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_aboutpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='mission_text',
            field=models.TextField(default="Le Guide du Potager Tropical accompagne les maraîchers urbains, périurbains et ruraux vers une production performante, rentable et résiliente face aux réalités climatiques tropicales.\n\nNos articles et fiches techniques intègrent l'ensemble des approches agronomiques : les itinéraires techniques conventionnels (gestion raisonnée des engrais minéraux NPK, protection phytosanitaire homologuée et conduite intensive) ainsi que les méthodes agro-écologiques et biologiques (amendements organiques, biopesticides locaux au neem, santé des sols vivants et paillage protecteur). Chaque producteur y trouve les protocoles, les dosages rigoureux et les conseils pratiques adaptés à ses objectifs de rendement.", help_text='Prend en charge le formatage texte ou HTML riche (<p>, <strong>, etc.)', verbose_name='Texte de présentation & Mission'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='mission_title',
            field=models.CharField(default='Notre Mission & Approche Maraîchère', max_length=200, verbose_name='Titre de la mission'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='pillar_1_desc',
            field=models.TextField(default='Goutte-à-goutte de précision, micro-aspersion, paillage protecteur et pilotage hydrique sous forte évapotranspiration.', verbose_name='Pilier 1 - Description'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='pillar_1_title',
            field=models.CharField(default="Gestion de l'Eau & Irrigation", max_length=150, verbose_name='Pilier 1 - Titre'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='pillar_2_desc',
            field=models.TextField(default='Plans de fertilisation équilibrés combinant apports minéraux raisonnés (NPK, urée) et amendements organiques pour maximiser les récoltes.', verbose_name='Pilier 2 - Description'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='pillar_2_title',
            field=models.CharField(default='Nutrition des Sols & Rendements', max_length=150, verbose_name='Pilier 2 - Titre'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='pillar_3_desc',
            field=models.TextField(default='Stratégies de défense des cultures articulant traitements conventionnels homologués, barrières physiques et biopesticides locaux.', verbose_name='Pilier 3 - Description'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='pillar_3_title',
            field=models.CharField(default='Protection Raisonnée & Biocontrôle', max_length=150, verbose_name='Pilier 3 - Titre'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='subtitle',
            field=models.CharField(default='Manuel de Maraîchage Tropical : Pratiques Conventionnelles & Agro-écologiques', max_length=300, verbose_name='Sous-titre / Slogan'),
        ),
    ]
