# Generated by Django 5.1.15 on 2026-08-15 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('characteristics', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='families/')),
                ('is_premium', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Plant Families',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('usage_tips', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tools/')),
                ('category', models.CharField(choices=[('travail_du_sol', 'Travail du Sol'), ('semis_plantation', 'Semis & Plantation'), ('entretien_arrosage', 'Entretien & Arrosage'), ('recolte', 'Récolte'), ('protection', 'Protection & Serre')], default='travail_du_sol', max_length=50)),
                ('is_premium', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=200)),
                ('sowing_period', models.CharField(max_length=200)),
                ('harvest_period', models.CharField(max_length=200)),
                ('care_tips', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='vegetables/')),
                ('is_premium', models.BooleanField(default=False)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vegetables', to='glossary.plantfamily')),
            ],
        ),
    ]
