# Generated by Django 5.2.17 on 2026-09-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='tropical_tips',
            field=models.TextField(blank=True, verbose_name='Astuces en climat tropical/sahélien'),
        ),
        migrations.AddField(
            model_name='vegetable',
            name='cycle_duration_days',
            field=models.PositiveIntegerField(default=90, verbose_name='Durée du cycle de culture (jours)'),
        ),
        migrations.AddField(
            model_name='vegetable',
            name='heat_tolerance',
            field=models.CharField(choices=[('faible', 'Faible (< 28°C, sensible à la chaleur)'), ('moyenne', 'Moyenne (28°C - 34°C)'), ('haute', 'Excellente (> 35°C, forte résistance sahélienne)')], default='moyenne', max_length=30, verbose_name='Tolérance thermique'),
        ),
        migrations.AddField(
            model_name='vegetable',
            name='sun_exposure',
            field=models.CharField(choices=[('plein_soleil', 'Plein soleil tropical'), ('mi_ombre', 'Mi-ombre / Ombrière 30-50% conseillée'), ('ombre', 'Ombragé sous canopée')], default='plein_soleil', max_length=30, verbose_name='Exposition au soleil tropical'),
        ),
        migrations.AddField(
            model_name='vegetable',
            name='tropical_season',
            field=models.CharField(choices=[('toute_annee', "Toute l'année (avec irrigation)"), ('saison_seche_fraiche', 'Saison sèche fraîche (Octobre - Février)'), ('saison_seche_chaude', 'Saison sèche chaude (Mars - Mai)'), ('hivernage', 'Saison des pluies / Hivernage (Juin - Septembre)')], default='toute_annee', max_length=50, verbose_name='Saison tropicale optimale'),
        ),
        migrations.AddField(
            model_name='vegetable',
            name='tropical_varieties',
            field=models.CharField(blank=True, help_text='Ex: Mongal F1, Nadira F1, Clemson Spineless, Habanero...', max_length=255, verbose_name='Variétés tropicales adaptées'),
        ),
        migrations.AddField(
            model_name='vegetable',
            name='water_requirement',
            field=models.CharField(choices=[('faible', 'Faible (tolère les stress hydriques)'), ('modere', 'Modéré'), ('eleve', 'Élevé (arrosage régulier / paillage obligatoire)')], default='modere', max_length=30, verbose_name='Besoins en eau / irrigation'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.CharField(choices=[('travail_du_sol', 'Travail du Sol & Préparation des Planches'), ('semis_plantation', 'Semis & Pépinière Tropicale'), ('entretien_arrosage', 'Irrigation & Paillage Protecteur'), ('recolte', 'Récolte'), ('protection', 'Ombrières & Filets Anti-insectes')], default='travail_du_sol', max_length=50),
        ),
        migrations.AlterField(
            model_name='vegetable',
            name='care_tips',
            field=models.TextField(verbose_name="Conseils de culture & d'entretien"),
        ),
        migrations.AlterField(
            model_name='vegetable',
            name='harvest_period',
            field=models.CharField(max_length=200, verbose_name='Période de récolte'),
        ),
        migrations.AlterField(
            model_name='vegetable',
            name='sowing_period',
            field=models.CharField(max_length=200, verbose_name='Période de semis'),
        ),
    ]
