# Generated by Django 5.2.17 on 2026-09-20 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0002_tool_tropical_tips_vegetable_cycle_duration_days_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantfamily',
            options={'ordering': ['name'], 'verbose_name_plural': 'Plant Families'},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='vegetable',
            options={'ordering': ['name']},
        ),
    ]
