# Generated by Django 5.2.17 on 2026-09-20 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0003_alter_plantfamily_options_alter_tool_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('semis', 'Semis & Plantations'), ('recolte', 'Récoltes')], default='semis', max_length=20, verbose_name='Action')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], verbose_name='Mois')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes / Conseils spécifiques pour ce mois')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('vegetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to='glossary.vegetable', verbose_name='Légume')),
            ],
            options={
                'verbose_name': 'Entrée de calendrier',
                'verbose_name_plural': 'Calendrier Cultural',
                'ordering': ['month', 'action', 'vegetable__name'],
                'unique_together': {('vegetable', 'action', 'month')},
            },
        ),
    ]
