# Generated by Django 5.2.17 on 2026-09-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pulse_delivery_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Carte Bancaire / Stripe'), ('orange_money', "Orange Money (Afrique de l'Ouest)"), ('wave', "Wave (Afrique de l'Ouest)"), ('mtn_money', 'MTN Mobile Money'), ('chariow', 'Chariow (Mobile Money & Carte)')], max_length=30),
        ),
    ]
