# Generated by Django 5.2.17 on 2026-09-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_payment_pulse_delivery_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('chariow', 'Chariow (Mobile Money & Carte)')], default='chariow', max_length=30),
        ),
    ]
