# Generated by Django 5.2.17 on 2026-09-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_payment_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('monthly', 'Mensuel'), ('yearly', 'Annuel')], max_length=20, unique=True, verbose_name='Type de formule')),
                ('name', models.CharField(help_text='Ex: Mensuel, Annuel', max_length=100, verbose_name='Nom affiché')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('currency', models.CharField(default='XOF', max_length=10, verbose_name='Devise')),
                ('approx_eur', models.CharField(blank=True, default='', max_length=50, verbose_name='Équivalence indicative (ex: ~4€)')),
                ('discount_badge', models.CharField(blank=True, default='', max_length=50, verbose_name='Badge promotionnel (ex: -30%)')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='Durée en jours')),
                ('chariow_product_id', models.CharField(blank=True, max_length=100, verbose_name='ID Produit Chariow (optionnel)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveIntegerField(default=1, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': "Formule d'abonnement",
                'verbose_name_plural': "Formules d'abonnement",
                'ordering': ['order', 'price'],
            },
        ),
    ]
