# Generated by Django 5.2.17 on 2026-09-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscriptionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Ex: Idéal pour un cycle complet de culture', max_length=200, verbose_name='Courte description'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Formule recommandée'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan_type',
            field=models.CharField(choices=[('monthly', 'Mensuel (2 500 XOF / ~4€)'), ('seasonal', 'Saison Potager - 3 Mois (5 000 XOF / ~8€)'), ('yearly', 'Annuel (15 000 XOF / ~23€)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='discount_badge',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Badge promotionnel (ex: -30% ou Recommandé)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('monthly', 'Mensuel'), ('seasonal', 'Saison Potager (3 Mois)'), ('yearly', 'Annuel')], max_length=20, unique=True, verbose_name='Type de formule'),
        ),
    ]
