# Generated by Django 5.2.17 on 2026-09-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='climate_zone',
            field=models.CharField(choices=[('sahelien', 'Zone Sahélienne (aride, harmattan, saison sèche longue)'), ('soudano_sahelien', 'Zone Soudano-Sahélienne (semi-aride)'), ('tropical_humide', 'Zone Tropicale Humide / Côtière'), ('equatorial', 'Zone Équatoriale / Forêt (forte humidité permanente)'), ('insulaire', 'Zone Insulaire Tropicale (Caraïbes / Océan Indien)')], default='sahelien', max_length=50, verbose_name='Zone agro-climatique'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, default='Sénégal', max_length=100, verbose_name='Pays / Territoire'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='garden_type',
            field=models.CharField(choices=[('potager_sol', 'Potager maraîcher en pleine terre'), ('hors_sol_bacs', 'Cultures hors-sol / Bacs & Tables maraîchères'), ('micro_jardin', 'Micro-jardin urbain / Cour intérieure'), ('perirubain', 'Exploitation agro-écologique périurbaine')], default='potager_sol', max_length=50, verbose_name='Type de potager'),
        ),
    ]
