# Generated by Django 5.2.17 on 2026-09-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='failed_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Tentatives échouées'),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='purpose',
            field=models.CharField(choices=[('registration', "Confirmation d'inscription"), ('email_change', "Changement d'adresse email"), ('password_reset', 'Réinitialisation de mot de passe')], default='registration', max_length=25),
        ),
    ]
