# Generated by Django 5.1.15 on 2026-08-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('glossary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('symptoms', models.TextField()),
                ('treatment', models.TextField()),
                ('prevention', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='diseases/')),
                ('is_premium', models.BooleanField(default=True)),
                ('affected_vegetables', models.ManyToManyField(blank=True, related_name='diseases', to='glossary.vegetable')),
            ],
        ),
        migrations.CreateModel(
            name='Insect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('damage', models.TextField()),
                ('solution', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='insects/')),
                ('is_premium', models.BooleanField(default=True)),
                ('affected_vegetables', models.ManyToManyField(blank=True, related_name='insects', to='glossary.vegetable')),
            ],
        ),
    ]
