# Generated by Django 5.2.17 on 2026-09-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='favorable_season',
            field=models.CharField(blank=True, default='Saison des pluies / Forte hygrométrie', max_length=150, verbose_name='Période tropicale à haut risque'),
        ),
        migrations.AddField(
            model_name='disease',
            name='tropical_organic_treatment',
            field=models.TextField(blank=True, help_text='Ex: macération de feuilles de neem, cendre de bois tamisée, purin de moringa...', verbose_name='Recettes & Traitements bio tropicaux'),
        ),
        migrations.AddField(
            model_name='insect',
            name='favorable_season',
            field=models.CharField(blank=True, default='Saison sèche chaude & périodes de transition', max_length=150, verbose_name='Saison de forte pullulation'),
        ),
        migrations.AddField(
            model_name='insect',
            name='prevention_tips',
            field=models.TextField(blank=True, help_text='Ex: toiles moustiquaires/anti-insectes 50 mesh, cultures pièges...', verbose_name='Prévention physique & agro-écologique'),
        ),
        migrations.AddField(
            model_name='insect',
            name='tropical_bio_control',
            field=models.TextField(blank=True, help_text='Ex: macération piment-ail-savon noir, huile de neem pressée à froid...', verbose_name='Biocontrôle & Répulsifs naturels locaux'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='prevention',
            field=models.TextField(verbose_name='Mesures préventives'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptoms',
            field=models.TextField(verbose_name='Symptômes observés'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='treatment',
            field=models.TextField(verbose_name='Traitement général'),
        ),
        migrations.AlterField(
            model_name='insect',
            name='damage',
            field=models.TextField(verbose_name='Dégâts causés aux cultures'),
        ),
        migrations.AlterField(
            model_name='insect',
            name='description',
            field=models.TextField(verbose_name='Description du ravageur'),
        ),
        migrations.AlterField(
            model_name='insect',
            name='solution',
            field=models.TextField(verbose_name='Solutions curatives'),
        ),
    ]
