# Generated by Django 5.2.17 on 2026-09-20 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pests', '0002_disease_favorable_season_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disease',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='insect',
            options={'ordering': ['id']},
        ),
    ]
